# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'OnePage' do
pod 'AFNetworking'
pod 'MJExtension'
pod 'MBProgressHUD'
pod 'Masonry'
pod 'SDWebImage'
end

target 'OnePageTests' do

end

target 'OnePageUITests' do

end

